name: Deploy app to gcloud

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
        PR_NUMBER: ${{ github.event.number }}
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit. 
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        cache: 'pip'
    - name : setting up python   
      run: |
        cd app_verification
        pip install -r requirements.txt
        echo "requirements installed"

    - name: Running app deployment script
      env:
        PR_NUMBER: ${{ github.event.number }}
        USER_NAME: ${{ secrets.USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}
        SERVICE_ACCOUNT_SHUFFLER: ${{ secrets.GOOGLE_CREDENTIALS }}
        SHUFFLE_USER_TOKEN: ${{ secrets.SHUFFLE_USER_TOKEN }}
      run : |
        cd app_verification
        python app_deploy.py    
  
