
name: Shaklin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Print
      run: |
        echo "Hello"
        echo ${{ github.event.number }}
        echo ${ github.event.pull_request.number }
        echo ${{ github.event.pull_request.number }}
        
      
